PR for enabling parquet suites
NVIDIA/spark-rapids pull request #11366
Opened 2024-08-20 11:21 UTC by Feng-Jiang28

This pr is for enabling parquet suites for UT framework. 
Enabled suites include:
1. ParquetColumnIndexSuite
2. ParquetCompressionCodecPrecedenceSuite (1 test failed)
3. ParquetDeltaByteArrayEncodingSuite
4. ParquetDeltaEncodingSuite
5. ParquetDeltaLengthByteArrayEncodingSuite
6. ParquetFieldIdIOSuite
7. ParquetFileFormatSuite (1 test failed)

2024-08-21 10:56 UTC, Feng-Jiang28 commented on tests/pom.xml
> +                    <groupId>org.apache.parquet</groupId>
I made changes of the code by removing the parquet related dependencies while keeping parquet-column. I am not sure if I chose the rigtht dependency. Can you please have a look?

2024-08-21 13:14 UTC, jlowe reviewed
Dependencies looks a lot better.  Need to file the tracking issue but otherwise lgtm.

2024-08-21 13:14 UTC, jlowe commented on tests/src/test/spark330/scala/org/apache/spark/sql/rapids/utils/RapidsTestSettings.scala
> +    .exclude("Create parquet table with compression", KNOWN_ISSUE("To be added"))
Tracking issue needs to be filed and noted here.

2024-08-28 03:50 UTC, Feng-Jiang28 commented
build

2024-08-28 04:02 UTC, Feng-Jiang28 commented
build

2024-08-28 06:11 UTC, Feng-Jiang28 commented
build

2024-08-28 08:59 UTC, Feng-Jiang28 commented
build

2024-08-29 06:35 UTC, Feng-Jiang28 commented
build

2024-08-29 11:32 UTC, Feng-Jiang28 commented
build

2024-08-30 02:36 UTC, Feng-Jiang28 commented
build

2024-09-04 09:34 UTC, Feng-Jiang28 commented
build

2024-09-06 03:56 UTC, Feng-Jiang28 commented
build

2024-09-11 03:05 UTC, Feng-Jiang28 commented
build

2024-09-11 08:39 UTC, Feng-Jiang28 commented
build

2024-09-18 02:05 UTC, Feng-Jiang28 commented
build

2024-09-18 06:06 UTC, thirtiseven reviewed
Are `output4.parquet` and `.output4.parquet.crc` added on purpose?

2024-09-23 03:13 UTC, Feng-Jiang28 commented
build

2024-09-23 08:09 UTC, binmahone requested changes

2024-09-23 08:09 UTC, binmahone commented on scala2.13/tests/pom.xml
> +                    <version>1.12.2</version>
use variable substitution?

2024-09-23 08:09 UTC, binmahone commented on tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites/RapidsParquetColumnIndexSuite.scala
> +  testRapids("test reading unaligned pages - test all types") {
nothing is exluded from RapidsParquetColumnIndexSuite?

2024-09-23 09:05 UTC, Feng-Jiang28 commented
build

2024-09-23 09:23 UTC, Feng-Jiang28 commented
build

2024-09-24 03:04 UTC, thirtiseven reviewed
LGTM but not a pom change expert

2024-09-24 06:15 UTC, binmahone approved these changes

2024-09-24 06:44 UTC, GaryShen2008 approved these changes

2024-09-24 06:44 UTC, merged