Scala UDF will compile child expressions in Project
NVIDIA/spark-rapids pull request #1153
Opened 2020-11-18 08:43 UTC by wjxiz1992

Signed-off-by: Allen Xu <allxu@nvidia.com>

Co-authored-by: Alessandro Bellina <abellina@nvidia.com>

This PR aims to resolve https://github.com/NVIDIA/spark-rapids/issues/1079.

The current fix lets the compiler compile Logical Plan recursively.

2020-11-18 08:49 UTC, wjxiz1992 commented
Hi @abellina, as we discussed offline, the current fix can solve the `explode` issue, but not perfect yet. Can you guide me here for a better solution?

2020-12-02 16:36 UTC, abellina commented on udf-compiler/src/test/scala/com/nvidia/spark/OpcodeSuite.scala
> +
@wjxiz1992 there's a missing `}` here.

2020-12-02 17:12 UTC, abellina commented
The physical plan for the explode test is:
```
== Physical Plan ==
Generate explode(split(x#5, ,, -1)), [x#5], false, [new#8]
+- Exchange RoundRobinPartitioning(1), false, [id=#9]
   +- LocalTableScan [x#5]
```

which looks correct to me.

The physical plan for the `flatten` test isn't. Do you expect this to work for an expression in a `flatten`? If so, this approach seems to fail there:

```
== Physical Plan ==
*(1) Project [x#5, flatten(UDF(x#5)) AS new#10]
+- Exchange RoundRobinPartitioning(1), false, [id=#9]
   +- LocalTableScan [x#5]
```

2020-12-02 17:20 UTC, abellina commented
Looking at this more it seems the `flatten` case is being looked at, but the UDF doesn't compile:

```
org.apache.spark.SparkException: Unsupported type for new:scala.collection.mutable.ArrayOps$ofRefProject [x#5, flatten(UDF(x#5)) AS new#10]
```

It looks to be a test issue.

2020-12-10 14:56 UTC, jlowe commented
Is this critical for the 0.3 release?  We are wrapping up the 0.3 release very soon, so this probably should be retargeted to branch-0.4.

2020-12-14 15:48 UTC, jlowe requested changes
Marking this as changes needed since it is still targeting branch-0.3 despite the PR project being set to Release 0.4.

2020-12-18 03:46 UTC, wjxiz1992 commented
Rebased on branch-0.4.
Hi @abellina can you take another look at this? the Flatten test case has been removed.

2020-12-18 15:11 UTC, jlowe commented
build

2020-12-18 22:09 UTC, jlowe approved these changes
Thanks for updating to 0.4.  Looks OK to me, but it would be good for @abellina to review as well before committing.

2021-01-05 14:36 UTC, abellina approved these changes

2021-01-05 14:36 UTC, merged