Added Shims for adding Databricks 14.3 Support [databricks]
NVIDIA/spark-rapids pull request #11635
Opened 2024-10-18 23:43 UTC by razajafri

This PR adds Shims for Databricks 14.3

2024-10-21 17:39 UTC, razajafri commented
build

2024-10-28 20:46 UTC, razajafri commented
@gerashegalov @mythrocks PTAL

2024-10-30 00:50 UTC, gerashegalov requested changes
need to upmerge

2024-10-30 00:50 UTC, gerashegalov commented on sql-plugin/src/main/spark350db/scala/com/nvidia/spark/rapids/spark350db/RapidsShuffleManager.scala
This file should be dropped after upmerging to branch-24.12

2024-10-30 00:50 UTC, gerashegalov commented on delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransactionBase.scala
Luckily git dedupes blobs but I wish we would not have 3 copies of these files in our repo

2024-10-30 17:27 UTC, razajafri commented on datagen/src/main/spark320/scala/org/apache/spark/sql/tests/datagen/DataGenExprShims.scala
> +{"spark": "350db"}
Good foresight. Will make the change

2024-10-30 17:28 UTC, razajafri commented on delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransactionBase.scala
Do we want to make the decision to shim these? @jlowe I know there is a reason you wanted to keep it the way it is today. Any reason we can't/shouldn't use shims?

2024-10-30 17:53 UTC, jlowe commented on delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransactionBase.scala
We would want to shim these if possible to reduce the duplication.

2024-10-31 21:23 UTC, razajafri commented on delta-lake/delta-spark332db/src/main/scala/com/databricks/sql/transaction/tahoe/rapids/GpuOptimisticTransactionBase.scala
I would like to do that as a part of a follow-on if that's ok

2024-10-31 21:25 UTC, razajafri commented
@gerashegalov I have addressed your concerns. PTAL

2024-10-31 22:44 UTC, gerashegalov commented on sql-plugin/src/main/spark350db143/scala/com/nvidia/spark/rapids/shims/spark350db143/SparkShimServiceProvider.scala
> +  val VERSION = DatabricksShimVersion(3, 5, 0)
```suggestion
  val VERSION = DatabricksShimVersion(3, 5, 0, "14.3")
```

2024-10-31 22:44 UTC, gerashegalov commented on sql-plugin/src/main/spark350db143/scala/com/nvidia/spark/rapids/shims/spark350db143/SparkShimServiceProvider.scala
> +    SparkEnv.get.conf.get("spark.databricks.clusterUsageTags.sparkVersion", "").startsWith("14.3.")
```suggestion
    DatabricksShimServiceProvider.matchesVersion("14.3.x")
```

2024-11-02 07:52 UTC, gerashegalov reviewed
LGTM. at least one copyright to update

2024-11-02 07:52 UTC, gerashegalov commented on sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/RapidsShuffleManager.scala
Update copyright

2024-11-04 17:34 UTC, gerashegalov submitted a review, later dismissed

2024-11-04 22:30 UTC, gerashegalov commented
Re failing [package-tests (350db143, false)](https://github.com/NVIDIA/spark-rapids/actions/runs/11671607945/job/32498487969?pr=11635#logs) ,  need to make sure that the db buildvers are not included in the Github Workflow build matrix

2024-11-05 18:01 UTC, razajafri commented
> Re failing [package-tests (350db143, false)](https://github.com/NVIDIA/spark-rapids/actions/runs/11671607945/job/32498487969?pr=11635#logs) , need to make sure that the db buildvers are not included in the Github Workflow build matrix

Hang on, I will have to modify the workflow file and remove the change from pom.xml

2024-11-06 07:48 UTC, gerashegalov commented
build

2024-11-06 07:48 UTC, gerashegalov approved these changes
LGTM

2024-11-07 00:04 UTC, razajafri commented
build

2024-11-07 16:44 UTC, mythrocks approved these changes

2024-11-07 17:37 UTC, razajafri commented
build

2024-11-07 23:49 UTC, razajafri commented
> @razajafri Can you enable Databricks-14.3 in the pre-merge CI pipeline in this PR as below?
> 
> https://github.com/NVIDIA/spark-rapids/blob/branch-24.12/jenkins/Jenkinsfile-blossom.premerge-databricks#L94
> 
> `values '11.3', '12.2', '13.3', '14.3'`

I have updated it but this will turn the integration tests on. We don't want the integration tests to run against Databricks 14.3 because we aren't ready.

2024-11-08 16:34 UTC, razajafri commented
build

2024-11-08 18:21 UTC, razajafri commented
build

2024-11-08 18:21 UTC, razajafri commented
> build

AWS_INSUFFICIENT_INSTANCE_CAPACITY_FAILURE

2024-11-08 23:17 UTC, razajafri commented
build

2024-11-11 05:14 UTC, pxLi commented
build

2024-11-11 05:25 UTC, pxLi commented
> > build
> 
> AWS_INSUFFICIENT_INSTANCE_CAPACITY_FAILURE

this change requires 8 clusters (4 shims x 2 parallelism) for the CI, we are considering using other instance types or temply disable parallel run for databricks runtimes.

2024-11-13 02:42 UTC, gerashegalov approved these changes

2024-11-13 18:32 UTC, merged