Optimize mvn denpendency download scripts
NVIDIA/spark-rapids pull request #1416
Opened 2020-12-17 07:53 UTC by NvTimLiu

Move definition of the maven repo into 'version-def.sh', then by overwrite the repo URL
it can download either `SNAPSHOT` cuDF/spark-rapids jars from the internal repo, for the nightly integration tests;
or it can download the `pre-release` jars on the Sonatype repo, for the release verify integration tests. The default maven repo is internal one for the nightly SNAPSHOT integration tests.

2020-12-17 07:55 UTC, NvTimLiu commented
build

2020-12-17 08:30 UTC, pxLi submitted a review, later dismissed

2020-12-17 08:36 UTC, pxLi commented
Looks good if per-merge test and integration tests can pass w/ the script change

2020-12-17 15:34 UTC, jlowe submitted a review, later dismissed

2020-12-17 15:36 UTC, revans2 submitted a review, later dismissed

2020-12-18 02:09 UTC, NvTimLiu commented
fix merge conflicts

2020-12-18 02:09 UTC, NvTimLiu commented
build

2020-12-18 02:19 UTC, NvTimLiu commented on jenkins/spark-tests.sh
> +$MVN_GET_CMD -DremoteRepositories=$PROJECT_TEST_REPO \
Here we diff `PROJECT_VER/PROJECT_REPO` & `PROJECT_TEST_VER/PROJECT_TEST_REPO`.
We only release rapids-4-spark.jar(`PROJECT_VER`) onto Sonatype repo(`PROJECT_REPO`).
rapids-4-spark-udf-examples-`SNAPSHOT`.jar/rapids-4-spark-integration-tests-`SNAPSHOT`.jar(`PROJECT_TEST_VER`) are on internal repo(`PROJECT_TEST_REPO`)

2020-12-18 06:28 UTC, pxLi commented
build

2020-12-18 15:12 UTC, jlowe approved these changes

2020-12-18 15:12 UTC, jlowe requested changes

2020-12-18 15:12 UTC, jlowe commented on jenkins/version-def.sh
> +RROJECT_TEST_VER=${PROJECT_TEST_VER:-"0.4.0-SNAPSHOT"}
Just noticed this typo:
```suggestion
PROJECT_TEST_VER=${PROJECT_TEST_VER:-"0.4.0-SNAPSHOT"}
```

2020-12-30 06:04 UTC, NvTimLiu commented
build

2020-12-30 06:05 UTC, NvTimLiu commented on jenkins/version-def.sh
> +RROJECT_TEST_VER=${PROJECT_TEST_VER:-"0.4.0-SNAPSHOT"}
@jlowe  Thanks a lot!

2021-01-04 14:27 UTC, jlowe approved these changes
Looks good, thanks!

@NvTimLiu in the future, please avoid force-pushing to PRs that are being reviewed.  It makes it difficult to see what has changed since the last time a reviewer looked at the PR and often review comments become disconnected from the code.  It's better to merge up to the latest branch, and as a bonus Github won't dismiss prior approvals if the merge was clean after the approval.

2021-01-05 01:03 UTC, merged

2021-01-05 01:04 UTC, NvTimLiu commented
> Looks good, thanks!
> 
> @NvTimLiu in the future, please avoid force-pushing to PRs that are being reviewed. It makes it difficult to see what has changed since the last time a reviewer looked at the PR and often review comments become disconnected from the code. It's better to merge up to the latest branch, and as a bonus Github won't dismiss prior approvals if the merge was clean after the approval.

Got it, thanks!