Test to track RAPIDS-side issues re SPARK-32639
NVIDIA/spark-rapids pull request #1578
Opened 2021-01-25 19:33 UTC by gerashegalov

This PR closes #1463. The test documents the scenario that fails on Spark (CPU) prior to Spark 3.1.0. 

It results in an executor JVM crash on GPU #1576. Since xfail does not handle the process crash gracefully and fails pytest, skip is used instead.

2021-01-25 20:29 UTC, gerashegalov commented
build

2021-01-25 20:30 UTC, jlowe requested changes

2021-01-25 20:30 UTC, jlowe commented on integration_tests/src/main/python/parquet_test.py
Need to add 2021 copyrights

2021-01-25 21:19 UTC, jlowe approved these changes

2021-01-25 21:52 UTC, jlowe commented
build

2021-01-26 01:25 UTC, pxLi commented
build

2021-01-26 17:38 UTC, merged