[WIP] update alluxio instruction on GCP dataproc
NVIDIA/spark-rapids pull request #1778
Opened 2021-02-19 21:55 UTC by mengdong

[WIP] update alluxio instruction on GCP dataproc

2021-02-21 06:03 UTC, sameerz requested changes

2021-02-23 02:43 UTC, mengdong reviewed
add fixes

2021-02-23 02:43 UTC, mengdong commented on docs/get-started/getting-started-alluxio.md
> +export CLUSTER_NAME=nvspark-dataproc-alluxio1
fixed

2021-02-23 02:43 UTC, mengdong commented on docs/get-started/getting-started-alluxio.md
> +    --image-version=preview-ubuntu \
fixed

2021-02-23 02:43 UTC, mengdong commented on docs/get-started/getting-started-alluxio.md
> +    --initialization-actions gs://${GCS_BUCKET}/alluxio-dataproc.sh,gs://goog-dataproc-initialization-actions-${REGION}/gpu/install_gpu_driver.sh,gs://goog-dataproc-initialization-actions-${REGION}/r
I've added the location but the script needs to be updated

2021-02-23 02:44 UTC, mengdong commented on docs/get-started/getting-started-alluxio.md
> +    --metadata alluxio_root_ufs_uri="gs://${GCS_BUCKET}/tpcds",gpu-driver-provider="NVIDIA",rapids-runtime="SPARK",alluxio_site_properties="alluxio.master.mount.table.root.option.fs.gcs.accessKeyId='
fixed

2021-03-01 04:19 UTC, mengdong commented
Close this one and reopen when Alluxio updated their init script

2021-03-01 04:19 UTC, closed without merging