Update docs for Databricks 8.2 ML
NVIDIA/spark-rapids pull request #2631
Opened 2021-06-08 07:53 UTC by sameerz

This is a partial update for the Databricks documentation.  

@viadea can you recommend an init script for users to run 21.06 on 7.3 ML that installs the CUDA 11 toolkit?

2021-06-08 18:06 UTC, tgravescs commented on docs/get-started/getting-started-databricks.md
> +version to match.  Users wishing to try 21.06 on Databricks 7.3 LTS ML will need to install the CUDA
do we want to give them example init script that does this?

2021-06-08 18:13 UTC, abellina commented on docs/get-started/getting-started-databricks.md
> +runs CUDA 11.0, wand initialization scripts for version 21.06 will install the matching cudf
```suggestion
runs CUDA 11.0, and initialization scripts for version 21.06 will install the matching cudf
```

2021-06-08 18:41 UTC, viadea commented
> This is a partial update for the Databricks documentation.
> 
> @viadea can you recommend an init script for users to run 21.06 on 7.3 ML that installs the CUDA 11 toolkit?

@sameerz I just submitted a PR to add a new init script to install cuda 11.0 with latest 21.06 jars. https://github.com/NVIDIA/spark-rapids/pull/2638

2021-06-08 19:07 UTC, tgravescs submitted a review, later dismissed

2021-06-08 21:34 UTC, viadea commented
@sameerz  Do you want to change the section:
`spark.executorEnv.PYTHONPATH /databricks/jars/rapids-4-spark_2.12-0.4.1.jar:/databricks/spark/python`
to use 21.06 plugin jar?

2021-06-09 05:05 UTC, viadea requested changes
`spark.executorEnv.PYTHONPATH /databricks/jars/rapids-4-spark_2.12-0.4.1.jar:/databricks/spark/python` needs to be changed.

2021-06-09 06:05 UTC, sameerz commented
> `spark.executorEnv.PYTHONPATH /databricks/jars/rapids-4-spark_2.12-0.4.1.jar:/databricks/spark/python` needs to be changed.

Done

2021-06-09 06:27 UTC, viadea approved these changes

2021-06-09 06:29 UTC, sameerz commented
build

2021-06-09 09:16 UTC, pxLi approved these changes

2021-06-09 09:16 UTC, merged