Remove unnecessary copies of ParquetCachedBatchSerializer
NVIDIA/spark-rapids pull request #2948
Opened 2021-07-16 14:58 UTC by razajafri

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

2021-07-16 17:38 UTC, razajafri commented
build

2021-07-16 17:42 UTC, jlowe reviewed
Looks like a spark320 version was missed?

2021-07-16 18:06 UTC, razajafri commented
> Looks like a spark320 version was missed?

Sorry, I left it out for the draft, but forgot to remove it post our meeting

2021-07-16 18:06 UTC, razajafri commented
build

2021-07-16 18:17 UTC, jlowe approved these changes

2021-07-16 18:19 UTC, jlowe requested changes
Actually the documentation does need to be changed here.  The cache docs refer to a table showing different classes for each Spark version, and those are being deleted in this PR.

2021-07-16 18:46 UTC, jlowe approved these changes

2021-07-16 18:46 UTC, razajafri commented
build

2021-07-16 19:19 UTC, jlowe requested changes
It looks like jenkins/spark-tests.sh also needs to be updated since it tries to pick the shim-specific class.

2021-07-19 15:50 UTC, razajafri commented
build

2021-07-19 15:58 UTC, jlowe commented on jenkins/spark-tests.sh
>    SHIM_PACKAGE=$(echo ${SPARK_VER} | sed 's/\.//g' | sed 's/-SNAPSHOT//')
This is no longer needed.
```suggestion
```

2021-07-19 23:08 UTC, razajafri commented
build

2021-07-20 13:26 UTC, jlowe approved these changes

2021-07-20 20:17 UTC, merged