Sanitize column names in ParquetCachedBatchSerializer before writing to Parquet [databricks]
NVIDIA/spark-rapids pull request #4258
Opened 2021-12-01 22:29 UTC by razajafri

There is a case where we use the original schema sent by Spark which has names that haven't been `sanitized`. 

This PR sets the names before creating a Hadoop conf.

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

2021-12-01 22:29 UTC, razajafri commented
build

2021-12-02 00:33 UTC, razajafri commented
build

2021-12-02 08:24 UTC, gerashegalov commented
can you create, reference an issue that is being solved by this PR?

2021-12-02 08:26 UTC, gerashegalov commented on sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
> +    originalSchema.zip(schemaToCopyNamesFrom).map(t => t._1.withName(t._2.name))
nit: prefer pattern-match to _1, _2, e.g.:
```scala
    originalSchema.zip(schemaToCopyNamesFrom).map { 
      case (origAttr, newAttr) => origAttr.withName(newAttr.name)
    }
```

2021-12-03 13:51 UTC, razajafri commented
build

2021-12-03 18:40 UTC, gerashegalov commented
#3879 is an epic. What point of #3879 are you working on? It sounds that you are fixing a bug. Can you point to a github bug issue with the problem description (repro and exception) or create one if there is none yet.

2021-12-06 05:13 UTC, razajafri commented
> #3879 is an epic. What point of #3879 are you working on? It sounds that you are fixing a bug. Can you point to a github bug issue with the problem description (repro and exception) or create one if there is none yet.

Sorry, I pasted the wrong link. I have updated the description to point to the nvbug

2021-12-06 20:04 UTC, jlowe submitted a review, later dismissed

2021-12-06 20:12 UTC, mythrocks commented on sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala
> +    val origSelectedAttributesWithUnambiguousNames =
Just a nitpick. The result of `sanitizeColumnNames()` isn't used in all branches of the subsequent `if{}` statement. I wonder if we can't move this definition to the `else{}` block.

2021-12-06 20:14 UTC, mythrocks requested changes
Generally :+1:. Minor nitpick.

2021-12-06 21:02 UTC, mythrocks approved these changes

2021-12-06 21:02 UTC, razajafri commented
test

2021-12-06 21:03 UTC, razajafri commented
build

2021-12-07 01:08 UTC, merged