Fix the issue of exporting Column RDD [databricks]
NVIDIA/spark-rapids pull request #4335
Opened 2021-12-09 08:48 UTC by wbo4958

This PR is trying to fix https://github.com/NVIDIA/spark-rapids/issues/4334.

After 3.1.x (included), `ColumnarRDD(df)` can't extract RDD[Table] directly, instead it will involve columnar to row and row to column which causes perf bad. It turned out the exportColumnRdd is not passed to `GpuColumnarToRowExecParent`

2021-12-09 08:49 UTC, wbo4958 commented
build

2021-12-09 16:16 UTC, revans2 submitted a review, later dismissed

2021-12-09 16:20 UTC, jlowe submitted a review, later dismissed
Ideally the test should be written as an integration test using the public `ColumnarRdd` API to replicate what user code would do, but I'm OK with this being a followup.

2021-12-09 22:55 UTC, sameerz requested changes
Please retarget to 22.02, as we are in code freeze for 21.12 and this is not a data corruption, crash, or customer critical fix (at this time).

2021-12-10 04:35 UTC, wbo4958 commented
> Ideally the test should be written as an integration test using the public `ColumnarRdd` API to replicate what user code would do, but I'm OK with this being a followup.

Hmm, Seems the user can't get `ColumnarRdd` API from PySpark.

2021-12-10 04:35 UTC, wbo4958 commented
build

2021-12-10 05:18 UTC, sameerz approved these changes
Thanks for moving to 22.02.

2021-12-10 14:31 UTC, jlowe approved these changes

2021-12-10 14:31 UTC, jlowe commented
Premerge failed in what appears to be an unrelated Python env error.  Rekicking.

2021-12-10 14:31 UTC, jlowe commented
build

2021-12-13 02:34 UTC, wbo4958 commented
build

2021-12-13 05:45 UTC, merged