update pca example link in ml-integration.md
NVIDIA/spark-rapids pull request #4430
Opened 2021-12-23 02:52 UTC by nvliyuan

Signed-off-by: liyuan <yuali@nvidia.com>

update pca example link in ml-integration.md

2021-12-29 20:29 UTC, sameerz requested changes
21.12 is released at this point.  This fix is minor enough that we would not do a hotfix for 21.12, and we can make the change in 22.02.  Please retarget to 22.02.

2021-12-30 09:27 UTC, nvliyuan commented
> 21.12 is released at this point. This fix is minor enough that we would not do a hotfix for 21.12, and we can make the change in 22.02. Please retarget to 22.02.

retargeted to 22.02

2021-12-30 23:17 UTC, sameerz approved these changes

2022-01-04 19:44 UTC, jlowe approved these changes

2022-01-04 19:44 UTC, jlowe commented
build

2022-01-04 19:50 UTC, merged