Optimize DECIMAL128 sum aggregations [databricks]
NVIDIA/spark-rapids pull request #4688
Opened 2022-02-03 23:04 UTC by jlowe

Depends on rapidsai/cudf#10201.

This accelerates sum aggregations on DECIMAL128 by splitting up the 128-bit values into 32-bit chunks, summing the chunks separately into 64-bit accumulated values, and then reassembling the 128-bit value from the accumulated chunks (with overflow checking).  This changes what would normally force a cudf sort-based aggregation into one that can be hash-based which can significantly improve performance.  This also allows us to remove some of the DECIMAL128 overflow code.

2022-02-04 16:20 UTC, jlowe commented
build

2022-02-04 16:56 UTC, revans2 submitted a review, later dismissed
The main thing I would like to see is follow on work to do the same kind of thing for average. We also should look at SUM for window operations. I don't think it will be needed there because the data comes in sorted, but some of the cleanup that has been done to split decimal from others would be good there too.

2022-02-04 21:15 UTC, jlowe commented
build

2022-02-04 21:46 UTC, revans2 approved these changes

2022-02-05 23:28 UTC, abellina requested changes

2022-02-05 23:28 UTC, abellina commented on sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
> +  override lazy val postMerge: Seq[Expression] = postMergeAttr
this is the default value for `postMerge`, so we should not need this override.

2022-02-05 23:28 UTC, abellina commented on sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
> +  override lazy val postMerge: Seq[Expression] = postMergeAttr
same question for `postUpdate`

2022-02-08 16:11 UTC, jlowe commented
Tracked down the CI failure to a libcudf issue with sort-based sum aggregations not performing aggregations in the result type as hash-based aggregations do.  Filed rapidsai/cudf#10246.  In the meantime, I'll update this to pre-cast the inputs to avoid the issue.

2022-02-08 17:55 UTC, jlowe commented
@abellina your comments should now be addressed.

Note that this also includes a change to lower the batch size being used in hash_aggregate_tests for exercising out-of-core hash aggregate processing, as the 312db failure from the previous CI run was triggered by such processing.  We were _not_ seeing it in other CI runs because we weren't regularly exercising this code path, but we do with the new lower batch size value.  This adds approx 5 minutes of test time on my desktop (with 4-way parallelism), but it seems worth it for the extra coverage.

2022-02-08 17:55 UTC, jlowe commented
build

2022-02-08 17:59 UTC, revans2 approved these changes

2022-02-08 18:04 UTC, abellina commented
One more nit on an override

2022-02-08 18:20 UTC, jlowe commented on sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala
> +  override lazy val preMerge: Seq[Expression] = aggBufferAttributes
Fixed.

2022-02-08 18:20 UTC, jlowe commented
build

2022-02-08 18:58 UTC, abellina approved these changes

2022-02-08 22:17 UTC, merged