Enable merge schema reading on ORC
NVIDIA/spark-rapids pull request #5605
Opened 2022-05-24 08:58 UTC by sperlingxx

Fixes #135 
Fixes #5562

This is to enable merge schema reading on ORC format. Meanwhile, it fixes a bug which fails reading ORC data from multiple file schemas, such as: reading merged schemas of different partitions.  The root cause of the bug is multi-thread modification of a thread unsafe variable (broadcasted Hadoop Conf).

Signed-off-by: sperlingxx <lovedreamf@gmail.com>

2022-05-24 09:17 UTC, sperlingxx commented
build

2022-05-24 10:57 UTC, wbo4958 approved these changes

2022-05-24 14:01 UTC, revans2 commented
How are we handling the schema evolution that ORC supports on java? I documented it [here](https://github.com/rapidsai/cudf/issues/5447) for CUDF, but it turned out to be java specific.

2022-05-24 14:03 UTC, revans2 commented
https://github.com/apache/orc/blob/acbf0205e0919d16f7daf239c367fdd6dfb22ecc/java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java#L2122-L2249

shows what is supported and before we can call this fixed we will need tests to verify that all of these work out of the box.

2022-05-24 14:04 UTC, revans2 commented
Sorry I should add that it is for the types that we support. UNION is not supported so we can ignore it.

2022-05-24 14:04 UTC, revans2 requested changes
Need to do what I described above. At least adding in tests for the schema evolution described above.

2022-05-25 09:46 UTC, sperlingxx commented
@revans2, with some tests, I found spark-rapids can not handle schema evolution with rules ORC supports on java at all. And If I am not wrong, it is a definate non-trivial work to support all schema evolution rules of ORC.

2022-05-25 14:32 UTC, revans2 commented
@sperlingxx Yes it is non-trivial, but it should be doable. We have almost all of that working with cast. There are likely to be minor differences, but we should be able to make ti all work.

The part that scares me most is that we can still trigger schema evolution without mergeSchema. If I as a user pass in a schema myself when reading an ORC file I can run into similar situations.  If it is too large to do at once here, then we should split the work up into smaller issues along with an epic and work through them.

2022-05-25 19:00 UTC, sameerz commented
@sperlingxx can we retarget this to 22.08?

2022-05-26 03:27 UTC, sperlingxx commented
Close this PR since it doesn't address the issue.

2022-05-26 03:27 UTC, closed without merging

2022-05-26 06:15 UTC, sperlingxx commented
Hi @revans2, is this PR left a data consistency issue unsolved as well ? If any, could you elaborate the issue ? I have little clue on it. Thank you.

2022-05-26 14:39 UTC, revans2 commented
@sperlingxx sorry if I am not clear about this PR.

1.  This PR says it fixes #5562, but it does not.
2. This PR says it fixes  #135, but it just turns off checking if it was enabled. It does not fix any of the underlying issues with schema evolution.
Yes the check for merge schema is a hack and is not perfect when dealing with schema evolution. This is why we need to fix the underlying issues. Just deleting the check does not "fix" any of it. If you want to merge in this PR it increases the likelihood that we will hit these bugs, but it does not eliminate them.