[DOC]update docs after we upgrade xgboost4j jars to dlmc 1.6.1[skip ci]
NVIDIA/spark-rapids pull request #5778
Opened 2022-06-08 01:18 UTC by nvliyuan

since we update xgboost4j jars from [nvidia shipped version](https://repo1.maven.org/maven2/com/nvidia/xgboost4j-spark_3.0/1.4.2-0.3.0/) to [DLMC XGBoost 1.6.1](https://github.com/dmlc/xgboost), we need to update reference docs

2022-06-08 04:50 UTC, viadea requested changes

2022-06-08 04:50 UTC, viadea commented on docs/get-started/getting-started-alluxio.md
>        To verify that Alluxio is running, visit [http://RM_hostname:19999](http://RM_hostname:19999)
maybe we should remove the link here.

2022-06-08 11:28 UTC, nvliyuan commented on docs/get-started/getting-started-alluxio.md
>        To verify that Alluxio is running, visit [http://RM_hostname:19999](http://RM_hostname:19999)
updated

2022-06-08 19:00 UTC, viadea commented
@sameerz  @GaryShen2008  I am fine with the changes. Do you want to take a look at well?

2022-06-08 19:46 UTC, viadea commented
@nvliyuan  could you make sure the jupyter notebook works on Dataproc using "JupyterLab"?
If so, I am fine with keeping 1 Jupyter version notebook for GCP.

2022-06-09 05:27 UTC, nvliyuan commented
> Why are we removing the Zeppelin notebook?
> 
> Does PR only change the reference to DMLC only, or also update the mortgage example?

Because we don't have any Zeppelin notebooks in the spark-rapids-example repo, all provided demos are based on Jupiter notebook, maybe we should keep the demo in the same form. This is the only one zpln notebook in both repo, and the demo is the same.
The code also needs to update because the introduction is outofdate, the output log is different, the api need to update(Nvidia XGBoost:`setFeaturesCols`. -> DMLC: `setFeaturesCol`)

2022-06-09 08:34 UTC, nvliyuan commented
> @nvliyuan could you make sure the jupyter notebook works on Dataproc using "JupyterLab"?
> If so, I am fine with keeping 1 Jupyter version notebook for GCP.

It indeed has some issues in some situations with the DMLC 161 jar(seems if we set spark.task.resource.gpu.amount less than 1, it will schedule more than 1 task to a executor and it will hang) , mark this pr as draft and need more time to verify

2022-06-13 03:51 UTC, nvliyuan commented
> > @nvliyuan could you make sure the jupyter notebook works on Dataproc using "JupyterLab"?
> > If so, I am fine with keeping 1 Jupyter version notebook for GCP.
> 
> It indeed has some issues in some situations with the DMLC 161 jar(seems if we set spark.task.resource.gpu.amount less than 1, it will schedule more than 1 task to a executor and it will hang) , mark this pr as draft and need more time to verify

see https://github.com/dmlc/xgboost/issues/7986

2022-06-14 00:48 UTC, GaryShen2008 approved these changes

2022-06-14 04:20 UTC, GaryShen2008 commented
As I discussed with Yuan, the issue blocks the demo notebook to run successfully. So, I'd like to skip this PR in 22.06.

2022-07-13 16:16 UTC, viadea submitted a review, later dismissed

2022-07-13 16:16 UTC, viadea commented
@sameerz  @GaryShen2008  I approved this PR. Do you have any concern or comments ?

2022-07-27 15:52 UTC, viadea commented
@nvliyuan  lots of old commits are shown in this PR. Do you want to try this workaround to see if it works?
https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

2022-07-27 15:56 UTC, sameerz commented
Please fix (or resubmit) the PR so we can review only the changes intended.

2022-07-27 16:07 UTC, viadea commented
@nvliyuan Could you make sure the mortgage examples match the new version in https://github.com/NVIDIA/spark-rapids/pull/5990/files which @SurajAralihalli drafted?
I am thinking of merging the 2 PRs together in this PR.

2022-07-28 11:27 UTC, nvliyuan commented
@sameerz @viadea just merged #5778 and #5990 to #6132

2022-07-28 11:28 UTC, closed without merging