Address feedback in "Improve regular expression error messages" PR
NVIDIA/spark-rapids pull request #5970
Opened 2022-07-07 23:36 UTC by anthony-chang

Follow up to https://github.com/NVIDIA/spark-rapids/pull/5871 to address some feedback. 

Refactored `isSupportedRepetitionBase` into two separate functions `isSupportedRepetitionBase` and `getUnsupportedRepetitionBase`. 

Signed-off-by: Anthony Chang <antchang@nvidia.com>

2022-07-07 23:42 UTC, NVnavkumar requested changes

2022-07-07 23:42 UTC, NVnavkumar commented on sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
>                    s"${unsupportedTerm.toRegexString}", term.position)
```suggestion
              getUnsupportedRepetitionBase(term) match {
                 case Some(unsupportedTerm) =>
                    throw new RegexUnsupportedException(
                      s"cuDF does not support repetition of group containing: " +
                        s"${unsupportedTerm.toRegexString}", term.position)
                  case _ =>
               }
```

You can use a pattern match here to clean this up.

2022-07-07 23:43 UTC, NVnavkumar commented on sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
>                    s"${unsupportedTerm.toRegexString}", term.position)
There are a few more examples in the code as well.

2022-07-08 20:54 UTC, NVnavkumar commented on sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala
>                    s"${unsupportedTerm.toRegexString}", term.position)
Then what I would suggest is not to return an Option from `getUnsupportedRepetitionBase(term)`.  In this case throw this kind of exception in that method itself. Basically if that method cannot return the `RegexAST` you want, you should throw a more meaningful exception there.

2022-07-08 22:31 UTC, anthony-chang commented
build

2022-07-21 18:46 UTC, NVnavkumar approved these changes

2022-07-21 19:18 UTC, merged