Qualification tool output recommendations on a per sql query basis
NVIDIA/spark-rapids pull request #6092
Opened 2022-07-26 16:08 UTC by tgravescs

fixes https://github.com/NVIDIA/spark-rapids/issues/5502

This adds in an option to allow a user to get the recommendations at the per sql query level in addition to the application level.  If an application has a lot of sql queries, this lets you narrow it down further to figure out which queries might benefit from being on the GPU the most.

2 new output files rapids_4_spark_qualification_output_persql.log and rapids_4_spark_qualification_output_persql.csv for text format and then csv format, contents are the same between them for now.

output looks like:
```
==========================================================================================================================================================================================================================================================
|                              App Name|             App ID|SQL ID|                                            SQL Description|SQL DF Duration|GPU Opportunity|Estimated GPU Duration|Estimated GPU Speedup|Estimated GPU Time Saved|      Recommendation|
==========================================================================================================================================================================================================================================================
|Rapids Spark Profiling Tool Unit Tests|local-1622043423018|     1|                   count at QualificationInfoUtils.scala:94|           7143|           6719|               2716.79|                 2.62|                  4426.2|Strongly Recommended|
|Rapids Spark Profiling Tool Unit Tests|local-1622043423018|     3|                   count at QualificationInfoUtils.scala:94|           2052|           1660|                958.28|                 2.14|                 1093.71|         Recommended|
|Rapids Spark Profiling Tool Unit Tests|local-1622043423018|     2|                   count at QualificationInfoUtils.scala:94|           1933|           1551|                 911.3|                 2.12|                 1021.69|         Recommended|
|                           Spark shell|local-1651187225439|     0|                                       show at <console>:26|            498|            249|                 373.5|                 1.33|                   124.5|         Recommended|

```

2 new options added, one to turn this output on and one to control the size of the sql description printed. Default is 100 there.  The normal options qualification tool take apply to this table as well. Such as order and limiting number of rows.

This does not contain the UI changes.

2022-07-26 16:11 UTC, tgravescs commented
build

2022-07-26 16:30 UTC, tgravescs commented
looks like I didn't upmerge to latest, will update shortly

2022-07-26 16:37 UTC, tgravescs commented
build

2022-07-26 19:12 UTC, nartal1 reviewed
Overall looks good. Just a question on `perSqlInfo`

2022-07-26 19:53 UTC, tgravescs commented on tools/src/main/scala/org/apache/spark/sql/rapids/tool/qualification/QualificationAppInfo.scala
> +        Some(origPlanInfos.flatMap { pInfo =>
yes good catch

2022-07-26 20:03 UTC, tgravescs commented
build

2022-07-26 20:24 UTC, nartal1 approved these changes

2022-07-26 20:34 UTC, amahussein requested changes
The CSV file format may get corrupted by the SQL description.
The SQL descriptions seem to include ","
```
Spark shell,app-20210509200722-0001,105,Execution: ss_max-v2.4, iteration: 1, StandardRun=true,335,0,335.0,1.0,0.0,Not Recommended
```

The above row has two extra columns compared to other ones.

2022-07-26 20:36 UTC, tgravescs commented
ah yep, needs to replace those

2022-07-26 23:46 UTC, tgravescs commented
build

2022-07-27 01:41 UTC, pxLi commented
unrelated `Unable to find py4j in` failed the CI intermittently. let me retrigger

2022-07-27 01:42 UTC, pxLi commented
build

2022-07-27 02:49 UTC, amahussein approved these changes
This fixes the bug. It is concerning that the fix did not require any change in the unit tests.
Later, we may consider covering this in the unit tests.

LGTME.

2022-07-27 13:30 UTC, tgravescs commented
I'm going to merge this and followup with a test in separate pr.

2022-07-27 13:30 UTC, merged