Fix notebook and getting started examples
NVIDIA/spark-rapids pull request #6421
Opened 2022-08-26 02:53 UTC by rwlee

Getting started rewording, fix the notebook (running errors and un-parseable by dataproc jupyter instances), link fixes, and example script fixes.

The notebook for 22.08 training still does not work because it needs `spark.dynamicAllocation.enabled=false`. I have not had time to look into how to fix this issue.

2022-08-26 14:46 UTC, sameerz commented
@rwlee this is too late to get into 22.08.  Please retarget to 22.10.

2022-08-26 22:57 UTC, viadea requested changes

2022-08-26 22:57 UTC, viadea commented on docs/get-started/getting-started-gcp.md
> +the dataset for training.  The ETL query splits the data, saving 20% of the data in a seaprate GCS location training for evaluation.  Using the default notebook configuration the first stage should t
@rwlee in doc, each line should be < 100 characters. Could you split the long line into many small lines? 

Same for some other long times.

2022-09-01 10:44 UTC, nvliyuan commented
LGTM

2022-09-01 10:45 UTC, nvliyuan approved these changes
LGTM

2022-09-01 16:29 UTC, viadea submitted a review, later dismissed

2022-09-01 18:32 UTC, rwlee commented
build

2022-09-08 19:46 UTC, rwlee commented
build

2022-09-09 03:35 UTC, nvliyuan approved these changes

2022-09-09 08:11 UTC, rwlee commented
build

2022-09-09 08:20 UTC, rwlee commented
build

2022-09-09 15:03 UTC, jlowe commented
CI failed due to #6515.  Skipping CI since this is just changes to documentation.

2022-09-09 15:03 UTC, jlowe commented
build

2022-09-09 18:03 UTC, merged