Add pulls to GitHub project
NVIDIA/spark-rapids pull request #6743
Opened 2022-10-10 14:26 UTC by mattahrens

Adding new PRs to global spark-rapids GitHub project.  Uses same action as what we put in for issues.

2022-10-10 14:43 UTC, mattahrens commented
build

2022-10-11 01:03 UTC, pxLi commented on .github/workflows/add-pr-to-project.yml
> +  pull_request:
plz try: `pull_request_target`

`pull_request` from forked repo should not have access to prod secret

2022-10-11 01:30 UTC, pxLi requested changes
Please add the trigger event `pull_request_target` to the existing workflow https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/.github/workflows/add-to-project.yml#L20

e.g.
```
on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
```

2022-10-11 03:38 UTC, mattahrens commented
Thanks for the feedback.  I moved the pull request addition to the existing workflow.

2022-10-11 04:05 UTC, mattahrens commented
build

2022-10-11 04:08 UTC, pxLi approved these changes

2022-10-11 10:29 UTC, merged