[doc] Add diagnostic tool section to GCP Dataproc getting started page [skip ci]
NVIDIA/spark-rapids pull request #6755
Opened 2022-10-11 06:43 UTC by zhanga5

which will be included from spark-rapids-user-tools package

Signed-off-by: Alex Zhang <alex4zhang@gmail.com>

2022-10-11 07:22 UTC, GaryShen2008 commented
LGTM，but should target to branch-22.10.

2022-10-11 07:26 UTC, zhanga5 commented
> LGTM，but should target to branch-22.10.

updated

2022-10-11 11:01 UTC, mattahrens reviewed
Couple general comments:

1. I would recommend adding a link to the Diagnostic tool in the quick start guide table of contents near the top, below this line: "* [Tune applications on GPU cluster](#tune-applications-on-gpu-cluster)"
2. In general, we want to refer to our solution in public documentation as the "RAPIDS Accelerator for Apache Spark" and not as "Spark RAPIDS".    So you can change that accordingly in a couple places.

2022-10-12 00:37 UTC, GaryShen2008 commented on docs/get-started/getting-started-gcp.md
> +...
That's a good idea. Let's discuss in the requirement doc.

2022-10-12 01:35 UTC, zhanga5 commented on docs/get-started/getting-started-gcp.md
> +Diagnostic tool can be run to check GPU cluster with Spark RAPIDS environment is healthy and
refined

2022-10-12 01:35 UTC, zhanga5 commented on docs/get-started/getting-started-gcp.md
> +Please note, diagnostic tool supported
refined

2022-10-12 01:35 UTC, zhanga5 commented
> Couple general comments:
> 
> 1. I would recommend adding a link to the Diagnostic tool in the quick start guide table of contents near the top, below this line: "* [Tune applications on GPU cluster](#tune-applications-on-gpu-cluster)"
> 2. In general, we want to refer to our solution in public documentation as the "RAPIDS Accelerator for Apache Spark" and not as "Spark RAPIDS".    So you can change that accordingly in a couple places.

refined

2022-10-13 23:08 UTC, viadea requested changes

2022-10-13 23:08 UTC, viadea commented on docs/get-started/getting-started-gcp.md
> +is healthy and ready for Spark jobs, such as installed Nvidia driver version, cuda-toolkit, RAPIDS
```suggestion
is healthy and ready for Spark jobs, such as checking the version of installed NVIDIA driver version, cuda-toolkit, RAPIDS
```

2022-10-13 23:08 UTC, viadea commented on docs/get-started/getting-started-gcp.md
> +Accelerator and run some Spark test jobs etc. This tool also can be used by the frontline support
```suggestion
Accelerator and running Spark test jobs etc. This tool also can be used by the frontline support
```

2022-10-13 23:08 UTC, viadea commented on docs/get-started/getting-started-gcp.md
> +* Dataproc 2.0 with image of Debian 10 or Ubuntu 18.04 (Rocky8 is coming soon)
```suggestion
* Dataproc 2.0 with image of Debian 10 or Ubuntu 18.04 (Rocky8 support is coming soon)
```

2022-10-14 01:44 UTC, zhanga5 commented on docs/get-started/getting-started-gcp.md
> +is healthy and ready for Spark jobs, such as installed Nvidia driver version, cuda-toolkit, RAPIDS
refined

2022-10-14 01:44 UTC, zhanga5 commented on docs/get-started/getting-started-gcp.md
> +Accelerator and run some Spark test jobs etc. This tool also can be used by the frontline support
refined

2022-10-14 01:44 UTC, zhanga5 commented on docs/get-started/getting-started-gcp.md
> +* Dataproc 2.0 with image of Debian 10 or Ubuntu 18.04 (Rocky8 is coming soon)
refined

2022-10-14 05:46 UTC, zhanga5 commented on docs/get-started/getting-started-gcp.md
> +...
refined based on new requirement

2022-10-14 06:09 UTC, GaryShen2008 approved these changes

2022-10-14 06:09 UTC, GaryShen2008 commented
build

2022-10-14 06:24 UTC, merged