Add JDK11 to mvn-verify-check
NVIDIA/spark-rapids pull request #6901
Opened 2022-10-25 01:41 UTC by YanxuanLiu

Signed-off-by: YanxuanLiu <yanxuanl@nvidia.com>

fix #6788 

Add a step for JDK11 with spark shim head version

2022-10-25 01:43 UTC, pxLi commented on .github/workflows/mvn-verify-check.yml
> +      - uses: actions/checkout@v2 # refs/pull/:prNumber/merge
please upmerge the base ref, and we should use actions/checkout@v3 to avoid deprecations

2022-10-25 01:48 UTC, pxLi commented
per https://github.com/NVIDIA/spark-rapids/issues/6788#issuecomment-1284691848, 
we may also have a matrix to test specific minor versions, I think there could be another property list for testing jdk11 shims

2022-10-27 00:54 UTC, pxLi requested changes

2022-10-27 00:54 UTC, pxLi commented on .github/workflows/mvn-verify-check.yml
> +        version: ${{ needs.get-noSnapshot-versions-from-dist.outputs.sparkJDK11Versions }}
`[mvn[compile,RAT,scalastyle,docgen]: .github#L1](https://github.com/NVIDIA/spark-rapids/pull/6901/files#annotation_5406717646)
Error when evaluating 'strategy' for job 'verify-modules-with-jdk11'. .github/workflows/mvn-verify-check.yml (Line: 106, Col: 18): Unexpected type of value '312', expected type: Sequence.`

failed typing https://github.com/NVIDIA/spark-rapids/actions/runs/3328337589/attempts/1

2022-10-29 03:21 UTC, gerashegalov commented
We might need a conditional profile for jdk11  to deal with https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist

2022-11-01 05:02 UTC, gerashegalov commented on dist/pom.xml
> -            331
I think instead of just removing 331, we should file an issue to make 331 compile with JDK11, then comment 331 out with the link to the issue

2022-11-01 06:22 UTC, gerashegalov commented on dist/pom.xml
> -            331
331 should compile after #6962

2022-11-02 02:16 UTC, pxLi commented
build

2022-11-02 02:16 UTC, pxLi approved these changes

2022-11-02 05:43 UTC, merged