add hadoop-def.sh
NVIDIA/spark-rapids pull request #7269
Opened 2022-12-06 07:02 UTC by YanxuanLiu

Signed-off-by: YanxuanLiu <yanxuanl@nvidia.com>

fix part of https://github.com/NVIDIA/spark-rapids/issues/5849

##### 2 file types in this repo:
- Shell: add `hadoop-def.sh` just like `version-def.sh`. Input `SPARK_VER` as argument. It will output `BIN_HADOOP_VER` and `BIN_HADOOP_URL`
- Scala:

2022-12-07 04:16 UTC, YanxuanLiu commented
`hadoop-def.sh` outputs with different inputs:
```
$ . jenkins/hadoop-def.sh; echo $BIN_HADOOP_VER
bin-hadoop3.2
$ . jenkins/hadoop-def.sh 3.2.1  echo $BIN_HADOOP_VER
bin-hadoop3.2
$ . jenkins/hadoop-def.sh 3.3.0; echo $BIN_HADOOP_VER
bin-hadoop3
$ . jenkins/hadoop-def.sh 3.3.0-SNAPSHOT; echo $BIN_HADOOP_VER
bin-hadoop3.2
$ . jenkins/hadoop-def.sh 3.3.0 https://custom.url.example; echo $BIN_HADOOP_VER
bin-hadoop3.2
```

2022-12-07 14:21 UTC, YanxuanLiu commented
part of `spark-premerge-build.sh` outputs:
```
BIN_HADOOP_VER=bin-hadoop3.2
+ mvn -Dmaven.wagon.http.retryHandler.count=3 org.apache.maven.plugins:maven-dependency-plugin:2.8:get -B -s jenkins/settings.xml -P mirror-apache-to-urm -DremoteRepositories=https://urm.nvidia.com/artifactory/sw-spark-maven -Ddest=/home/yanxuanl/.download -DgroupId=org.apache -DartifactId=spark -Dversion=3.1.1 -Dclassifier=bin-hadoop3.2 -Dpackaging=tgz

...

export SPARK_HOME=/home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2
+ SPARK_HOME=/home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2
+ export PATH=/home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2/bin:/home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2/sbin:/home/yanxuanl/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/bin/remote-cli:/home/yanxuanl/.local/bin:/home/yanxuanl/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ PATH=/home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2/bin:/home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2/sbin:/home/yanxuanl/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/bin/remote-cli:/home/yanxuanl/.local/bin:/home/yanxuanl/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ tar zxf /home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2.tgz -C /home/yanxuanl/.download
+ rm -f /home/yanxuanl/.download/spark-3.1.1-bin-hadoop3.2.tgz
```

2023-01-13 00:56 UTC, pxLi commented on jenkins/spark-premerge-build.sh
> +wget -P $ARTF_ROOT https://archive.apache.org/dist/spark/spark-$SPARK_VER/spark-$SPARK_VER-$BIN_HADOOP_VER.tgz
lets make it internal art-based as default, could simply use 

[SPARK_REPO](https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/jenkins/version-def.sh#L46)
or $URM_URL

2023-01-13 00:57 UTC, pxLi commented on jenkins/spark-tests.sh
> +wget -P $ARTF_ROOT https://archive.apache.org/dist/spark/spark-$SPARK_VER/spark-$SPARK_VER-$BIN_HADOOP_VER.tgz
the same. At least in our CI, it would be nice to use internal artifact store. Would be better to use $SPARK_REPO to form the link

2023-01-13 00:58 UTC, pxLi commented on jenkins/hadoop-def.sh
> +if [[ ${#spark_version[@]} == 1 ]] && [[ `echo -e "${spark_version[0]}\n3.3.0" | sort -V | head -n 1` == "3.3.0" ]]; then # without suffix and spark version >= 3.3.0
nit: lets move the comment ahead the if statement to have more space to explain snapshot cases we have

2023-01-13 00:59 UTC, pxLi commented on jenkins/hadoop-def.sh
> +# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
nit: copyright header should be `2023`

2023-01-13 04:31 UTC, pxLi commented on jenkins/spark-tests.sh
nit: license header Copyright (c) 2019-**2023**

2023-01-13 04:31 UTC, pxLi commented
build

2023-01-13 04:33 UTC, pxLi commented
Lets keep the PR draft until all 3.3.0 released spark tarball are available at internal artifact store~

2023-01-13 04:35 UTC, pxLi commented
build

2023-01-13 06:11 UTC, pxLi requested changes
please update artifact paths~

2023-01-13 06:20 UTC, pxLi commented
build

2023-01-13 06:21 UTC, pxLi approved these changes

2023-01-13 08:02 UTC, merged