[WIP] Disable HiveTextReaders for CDH due to NVIDIA#7423
NVIDIA/spark-rapids pull request #7628
Opened 2023-01-31 21:37 UTC by sririshindra

Signed-off-by: Rishi <sririshindra@gmail.com>

CDH spark a little more robust/forgiving in reading certain inputs as compared to to upstream spark. spark-rapids follows upstream spark conventions and as such cdh users might see a discrepancy when reading an input on CPU vs GPU. In order to avoid that we are falling back on the CPU when Hive delimited text table reads are involved.

2023-01-31 21:52 UTC, mythrocks commented on sql-plugin/src/main/330cdh/scala/org/apache/spark/sql/hive/cdh/HiveOverrides.scala
> + * Copyright (c) 2019-2023, NVIDIA CORPORATION.
```suggestion
 * Copyright (c) 2023, NVIDIA CORPORATION.
```

2023-01-31 22:27 UTC, sameerz commented
build

2023-01-31 22:59 UTC, mythrocks commented on sql-plugin/src/main/330cdh/scala/org/apache/spark/sql/hive/cdh/HiveOverrides.scala
> +  def getHiveTableExecRule() = {
We should probably mention that this is a workaround for the mismatches listed in #7423.

2023-01-31 22:59 UTC, mythrocks requested changes
A couple of minor nitpicks, but this is looking good to me.

2023-02-01 18:20 UTC, sririshindra commented on sql-plugin/src/main/330cdh/scala/org/apache/spark/sql/hive/cdh/HiveOverrides.scala
> + * Copyright (c) 2019-2023, NVIDIA CORPORATION.
Done

2023-02-01 21:25 UTC, mythrocks approved these changes

2023-02-01 21:27 UTC, merged

2023-02-01 21:27 UTC, mythrocks commented
Thanks for fixing this, @sririshindra. I've merged this.