Bring back UCX 1.14
NVIDIA/spark-rapids pull request #8402
Opened 2023-05-25 18:16 UTC by abellina

Reverts (the revert): https://github.com/NVIDIA/spark-rapids/pull/7942

This updates the pom, dockerfile, and documentation to UCX 1.14.

2023-05-25 18:22 UTC, abellina commented
The CI issues we have seen here https://github.com/NVIDIA/spark-rapids/issues/7940 are related to pre-existing TCP keepalive issues in UCX.

2023-05-25 19:24 UTC, abellina commented
build

2023-05-29 18:00 UTC, sameerz requested changes

2023-05-29 18:00 UTC, sameerz commented on docs/additional-functionality/rapids-shuffle.md
> +https://github.com/openucx/ucx/releases/download/v1.14.0/ucx-v1.14.0-centos8-mofed5-cuda11.tar.bz2
```suggestion
https://github.com/openucx/ucx/releases/download/v1.14.0/ucx-1.14.0-centos8-mofed5-cuda11.tar.bz2
```

2023-05-31 13:50 UTC, abellina commented
build

2023-05-31 14:07 UTC, abellina commented
@sameerz let me know if this looks good. CI is building which will test fetching the jucx-1.14 jar and running a smoke test with it.

2023-05-31 18:37 UTC, abellina commented
@jlowe @revans2 @tgravescs if I could get some :eyes: from you that would be great.

2023-05-31 19:36 UTC, jlowe commented on docs/additional-functionality/rapids-shuffle.md
> +UCX support for CUDA 12 in RAPIDS Spark will be added in a future release.
```suggestion
UCX support for CUDA 12 in the RAPIDS Accelerator will be added in a future release.
```

2023-05-31 19:44 UTC, revans2 submitted a review, later dismissed
I did not actually test out the Dockerfiles, but I assume that someone did. If not please lat me know so I can revert my approval.

2023-05-31 19:48 UTC, jlowe approved these changes

2023-05-31 20:13 UTC, abellina commented
> I did not actually test out the Dockerfiles, but I assume that someone did. If not please lat me know so I can revert my approval.

I thought I re-ran this, but I obviously I missed something. I re-build all of them and found an issue, unfortunately, with Ubuntu 22.04 and the rdma-core that this builds and installs. I also found an inconsistency in the no-rdma version of the ubuntu example. Fixed both https://github.com/NVIDIA/spark-rapids/pull/8402/commits/0e22f2502629b4774a01001aa991a0f503baa4da. 

This are example dockerfiles. I'll need to edit these files for Ubuntu 22.04, but I'll need to do that as a separate PR and we can add an example for Ubuntu 22.04 specifically or make it obvious what the differences are.

2023-05-31 21:24 UTC, abellina commented
Found one more runtime issue with the dockerfile. I'll push shortly.

2023-05-31 22:39 UTC, jlowe approved these changes

2023-06-01 12:48 UTC, abellina commented
build

2023-06-01 16:53 UTC, sameerz approved these changes

2023-06-01 16:54 UTC, merged