Added 3.5.1-SNAPSHOT Shim
NVIDIA/spark-rapids pull request #9962
Opened 2023-12-05 19:10 UTC by razajafri

This PR adds shims for Spark 3.5.1-SNAPSHOT. 

**Changes Made:**
Pretty much the result of running 
```
mvn generate-sources -Dshimplify=true -Dshimplify.move=true -Dshimplify.overwrite=true -Dshimplify.add.shim=351 -Dshimplify.add.base=350
```

* The only files that were manually changed were `pom.xml` and `ShimServiceProvider.scala` to add the SNAPSHOT version to the `VERSIONNAMES`. 

* Removed some empty lines as a result of the above `Shimplify` command

**Tests:**
Some integration tests were run locally. The entire suite will be run after the CI support is added

This is a DRAFT until the CI support is added

2023-12-05 20:02 UTC, jlowe approved these changes

2023-12-05 20:32 UTC, andygrove submitted a review, later dismissed

2023-12-07 16:10 UTC, tgravescs commented
I'm assuming your decimal multiple is related to https://github.com/NVIDIA/spark-rapids/issues/9859...  If so pleas emake sure it fixes it all the way or we comment on that issue.  the shim is very hard to read, one calls mul128 the other calls multiply128. I haven't went and looked at those but one its hard to even see that diff so you should in the very least add a comment or point to issue and explain.

2023-12-07 16:59 UTC, razajafri commented
> the shim is very hard to read, one calls mul128 the other calls multiply128. I haven't went and looked at those but one its hard to even see that diff so you should in the very least add a comment or point to issue and explain.

I will go ahead and put in some comments to highlight the change

2023-12-07 18:04 UTC, razajafri commented
> I'm assuming your decimal multiple is related to https://github.com/NVIDIA/spark-rapids/issues/9859... If so pleas emake sure it fixes it all the way or we comment on that issue

Discussed this offline. I missed the division bit of the puzzle. Will verify division and post an update here

2023-12-08 03:50 UTC, razajafri commented
> > I'm assuming your decimal multiple is related to #9859... If so pleas emake sure it fixes it all the way or we comment on that issue
> 
> Discussed this offline. I missed the division bit of the puzzle. Will verify division and post an update here

I have verified the Decimal division and we match Spark 3.5.1 output. 

It turns out that we were always doing the right thing on the GPU for decimal division. So to match Spark bug for bug we should "fix" the versions Databricks 330+ and Spark versions 340+ by returning the bad answer. I have created an issue for that [here](https://github.com/NVIDIA/spark-rapids/issues/9998)

2023-12-18 19:38 UTC, razajafri commented
build

2023-12-18 22:02 UTC, razajafri commented
premerge failing due to an unrelated change

```
[2023-12-18T20:02:45.179Z] [ERROR] /home/ubuntu/spark-rapids/tests/src/test/scala/org/apache/spark/sql/rapids/metrics/source/MockTaskContext.scala:69: overriding method getKillReason in class TaskContext of type ()Option[String];
[2023-12-18T20:02:45.180Z]  method getKillReason has weaker access privileges; it should be public
[2023-12-18T20:02:45.180Z] [ERROR]   override private[spark] def getKillReason() = None
[2023-12-18T20:02:45.180Z] [ERROR]                               ^
[2023-12-18T20:02:45.180Z] [ERROR] one error found
```

2023-12-18 22:05 UTC, razajafri commented
@NvTimLiu @pxLi why is the premerge picking up databricks 13.3

2023-12-19 00:14 UTC, razajafri commented
build

2023-12-19 01:22 UTC, razajafri commented
build

2023-12-19 01:23 UTC, razajafri commented
> @NvTimLiu @pxLi why is the premerge picking up databricks 13.3

Nevermind, I saw that there is a function that checks if there are any changes in the Databricks shims in addition to the word `databricks` in the title of the PR

2023-12-19 05:35 UTC, razajafri commented
build

2023-12-19 16:42 UTC, razajafri commented
build

2023-12-19 18:09 UTC, razajafri commented
Connectivity problem 
```
...
Could not transfer artifact org.apache.hadoop:hadoop-project-dist:pom:3.1.1.7.1.7.1000-141 from/to cloudera-repo (https://repository.cloudera.com/artifactory/cloudera-repos/): Transfer failed for https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/hadoop/hadoop-project-dist/3.1.1.7.1.7.1000-141/hadoop-project-dist-3.1.1.7.1.7.1000-141.pom 500 Internal Server Error -> [Help 1]
```

2023-12-19 18:09 UTC, razajafri commented
build

2023-12-19 19:33 UTC, razajafri commented
build

2023-12-20 00:02 UTC, gerashegalov commented
build

2023-12-20 16:43 UTC, razajafri commented
build

2023-12-20 17:02 UTC, razajafri commented
build

2023-12-20 17:23 UTC, razajafri commented
I have reverted the tests for versions that we don't support yet. They will be added in other shims

2023-12-20 17:23 UTC, razajafri commented
build

2023-12-20 21:43 UTC, andygrove approved these changes

2023-12-20 21:48 UTC, gerashegalov requested changes

2023-12-20 21:48 UTC, gerashegalov commented on sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala
> +            arithmeticOverflowError("One or more rows overflow for Add operation.")
let us leave formatting-only changes to dedicated PRs

2023-12-20 21:48 UTC, gerashegalov commented on sql-plugin/src/main/spark311/scala/com/nvidia/spark/rapids/shims/ComputeSequenceSizes.scala
> +  }
The bottom portion L85-L111 in 311 and L98-L126 in 351 differ only in the require message let us refactor to minimize shimming

2023-12-20 21:48 UTC, gerashegalov commented on sql-plugin/src/main/spark350/scala/com/nvidia/spark/rapids/shims/api/python/ShimBasePythonRunner.scala
This file should be dropped thanks to #9902

2023-12-21 02:46 UTC, razajafri commented
Thanks for taking a look @gerashegalov 

PTAL

2023-12-21 02:48 UTC, razajafri commented
build

2023-12-21 04:56 UTC, gerashegalov approved these changes

2023-12-25 02:56 UTC, NvTimLiu approved these changes
LGTM

2023-12-25 02:57 UTC, NvTimLiu commented
Will we plan to run nightly integration tests against spark-3.5.1-SNAPSHOT?

2023-12-25 07:18 UTC, merged

2023-12-25 07:18 UTC, razajafri commented
> Will we plan to run nightly integration tests against spark-3.5.1-SNAPSHOT?

Yes, we do